version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - backend

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: db_name # need to be same than MYSQL_DATABASE
      WORDPRESS_DB_USER: $DB_USER # need to be same than MYSQL_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD # need to be same than MYSQL_PASSWORD
      WORDPRESS_ADMIN: $WP_ADMIN
      WORDPRESS_ADMIN_PASS: $WP_ADMIN_PASS
      WORDPRESS_ADMIN_EMAIL: $WP_ADMIN_EMAIL
      WORDPRESS_USER: $WP_USER
      WORDPRESS_USER_ROLE: $WP_USER_ROLE
      WORDPRESS_USER_PASS: $WP_USER_PASS
      WORDPRESS_USER_EMAIL: $WP_USER_EMAIL
    depends_on:
      - mariadb
    restart: always
    networks:
      - frontend
      - backend

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    networks:
      - frontend

volumes: 
  db_data:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/minummin/data/mariadb
  wp_data:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/minummin/data/wordpress

networks:
  frontend:
    name: frontend
  backend:
    name: backend